-- Test database setup 

CREATE DATABASE TEST_DB;
CREATE SCHEMA TEST_DB.DEV;

CREATE DATABASE APP_INTEGRATION;
CREATE SCHEMA APP_INTEGRATION.DEV;

---------------------------------------------------
CREATE DATABASE ANBDW_STAGE; 
CREATE SCHEMA ANBDW_STAGE.DEV; 
CREATE DATABASE ANBDW_DEV;